services:
  backend:
    image: ask2gaurav/codebasics_a1_backend
    build: 
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      MONGODB_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017"
      QDRANT_HOST: qdrant
    depends_on:
      - mongodb
      - qdrant
    develop:
      watch:
        - path: ./backend/requirements.txt
          action: rebuild
        - path: ./backend
          action: sync
          target: /app
          ignore:
            - __pycache__/
            - .venv/
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    image: ask2gaurav/codebasics_a1_frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: builder
    command: pnpm dev
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - "3000:3000"
    env_file: .env
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/pnpm-lock.yaml
          action: rebuild
        - path: ./frontend
          action: sync
          target: /app
          ignore:
            - node_modules/

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./config/mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: admin
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: adminpassword
  #     ME_CONFIG_MONGODB_URL: mongodb://admin:adminpassword@mongodb:27017/
  #   depends_on:
  #     - mongodb

  qdrant:
    image: qdrant/qdrant:v1.9.2
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
      - ./config/qdrant/config.yaml:/qdrant/config/custom_config.yaml:ro

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

volumes:
  mongodb_data:
  qdrant_data:
